// examples/02-framework-integration/next-openai/app/use-chat-attachments-append/page.tsx
'use client';

/* eslint-disable @next/next/no-img-element */
import { useChat } from '@ai-toolkit/react';
import { useRef, useState } from 'react';

export default function Page() {
  const { messages, sendMessage, status } = useChat();
  const [input, setInput] = useState('');

  const [files, setFiles] = useState<FileList | undefined>(undefined);
  const fileInputRef = useRef<HTMLInputElement>(null);

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-col gap-2 p-2">
        {messages.map(message => (
          <div key={message.id} className="flex flex-row gap-2">
            <div className="flex-shrink-0 w-24 text-zinc-500">{`${message.role}: `}</div>

            <div className="flex flex-col gap-2">
              {message.parts.map((part, index) => {
                if (part.type === 'text') {
                  return <div key={`${part.type}-${index}`}>{part.text}</div>;
                }
                if (part.type === 'file' && part.mediaType?.startsWith('image/')) {
                  return (
                    <div key={`${part.type}-${index}`}>
                      <img className="rounded-md w-60" src={part.url} alt={part.filename} />
                    </div>
                  );
                }
                return null;
              })}
            </div>
          </div>
        ))}
      </div>

      <form
        onSubmit={async event => {
          event.preventDefault();

          sendMessage({ text: input, files });

          setFiles(undefined);
          setInput('');

          if (fileInputRef.current) {
            fileInputRef.current.value = '';
          }
        }}
        className="fixed bottom-0 flex flex-col w-full gap-2 p-2"
      >
        <div className="fixed flex flex-row items-end gap-2 right-2 bottom-14">
          {files
            ? Array.from(files).map(attachment => {
                const { type } = attachment;

                if (type.startsWith('image/')) {
                  return (
                    <div key={attachment.name}>
                      <img
                        className="w-24 rounded-md"
                        src={URL.createObjectURL(attachment)}
                        alt={attachment.name}
                      />
                      <span className="text-sm text-zinc-500">{attachment.name}</span>
                    </div>
                  );
                }
                return null;
              })
            : ''}
        </div>
        <input
          type="file"
          onChange={event => {
            if (event.target.files) {
              setFiles(event.target.files);
            }
          }}
          multiple
          ref={fileInputRef}
        />
        <input
          value={input}
          placeholder="Send message..."
          onChange={e => setInput(e.target.value)}
          className="w-full p-2 bg-zinc-100"
          disabled={status !== 'ready'}
        />
      </form>
    </div>
  );
}

// examples/02-framework-integration/nuxt-openai/pages/use-chat-attachments-append/index.vue
<script setup lang="ts">
import { Chat } from '@ai-toolkit/vue';
import { convertFileListToFileUIParts } from '@ai-toolkit/ai';
import { computed, ref } from 'vue';

const chat = new Chat({});
const input = ref('');

const files = ref<FileList | null>(null);
const fileInputRef = ref<HTMLInputElement | null>(null);

const submit = async (e: Event) => {
  e.preventDefault();

  const fileParts = await convertFileListToFileUIParts(files.value ?? undefined);

  chat.sendMessage({
    role: 'user',
    parts: [...fileParts, { type: 'text', text: input.value }],
  });

  input.value = '';
  fileInputRef.value!.value = '';
  files.value = null;
};

const filesWithUrl = computed(() => {
  if (!files.value) return [];

  return Array.from(files.value).map(file => ({
    file,
    url: URL.createObjectURL(file),
  }));
});
</script>

<template>
  <div class="flex flex-col w-full max-w-md py-24 mx-auto stretch">
    <div
      v-for="message in chat.messages"
      :key="message.id"
      class="whitespace-pre-wrap"
    >
      <strong>{{ `${message.role}: ` }}</strong>
      {{
        message.parts
          .map(part => (part.type === 'text' ? part.text : ''))
          .join('')
      }}

      <div
        v-if="message.parts.some(part => part.type === 'file')"
        class="flex flex-row gap-2"
      >
        <img
          v-for="(attachment, index) in message.parts.filter(
            part => part.type === 'file',
          )"
          :key="`${message.id}-${index}`"
          :src="attachment.url"
          class="rounded-md size-20"
        />
      </div>
    </div>

    <form
      @submit.prevent="submit"
      class="fixed bottom-0 flex flex-col max-w-md gap-2 mb-8"
    >
      <div class="flex flex-row gap-2">
        <img
          v-for="file in filesWithUrl"
          :key="file.file.name"
          :src="file.url"
          class="rounded-md size-20"
        />
      </div>
      <input
        ref="fileInputRef"
        type="file"
        accept="image/*"
        multiple
        @change="files = ($event.target as HTMLInputElement).files"
      />
      <input
        class="w-full p-2 border border-gray-300 rounded shadow-xl"
        v-model="input"
        placeholder="Say something..."
      />
    </form>
  </div>
</template>
